backend:
  name: github
  repo: Sergey285830/fakel-site
  branch: main
  auth_type: pkce
  app_id: Ov23liklgtXDLXis0LRx

media_folder: "Fakel_Site/img"
public_folder: "img"
locale: 'ru'

collections:
  - name: "news"
    label: "Новости клуба"
    folder: "Fakel_Site/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Дата публикации", name: "date", widget: "datetime"}
      - {label: "Фотография", name: "thumbnail", widget: "image", required: false}
      - {label: "Текст новости", name: "body", widget: "markdown"}
  - name: "matches"
    label: "Матчи"
    folder: "Fakel_Site/matches"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Соперник", name: "opponent", widget: "string"}
      - {label: "Дата матча", name: "date", widget: "datetime"}
      - {label: "Счет", name: "score", widget: "string", required: false}
      - {label: "Отчет об игре", name: "body", widget: "markdown", required: false}
