backend:
  name: github
  repo: Sergey285830/fakel-site
  branch: main
  base_url: "https://footballclubfakel161.vercel.app/api"

media_folder: "Fakel_Site/img"
public_folder: "img"
locale: 'ru'

collections:
  - name: "data"
    label: "Данные сайта"
    files:
      - label: "Турнирная таблица"
        name: "standings"
        file: "Fakel_Site/data/standings.json"
        fields:
          - label: "Команды"
            name: "teams"
            widget: "list"
            fields:
              - {label: "Позиция", name: "position", widget: "number"}
              - {label: "Название", name: "name", widget: "string"}
              - {label: "Игры", name: "games", widget: "number"}
              - {label: "Победы", name: "wins", widget: "number"}
              - {label: "Ничьи", name: "draws", widget: "number"}
              - {label: "Поражения", name: "losses", widget: "number"}
              - {label: "Разница голов", name: "goals_diff", widget: "string"}
              - {label: "Очки", name: "points", widget: "number"}

      - label: "Последний матч"
        name: "latest_result"
        file: "Fakel_Site/data/latest_result.json"
        fields:
          - {label: "Турнир и дата", name: "match_info", widget: "string"}
          - {label: "Команда 1 (Хозяева)", name: "team1", widget: "string"}
          - {label: "Счет", name: "score", widget: "string"}
          - {label: "Команда 2 (Гости)", name: "team2", widget: "string"}
          - label: "События Команды 1"
            name: "events1"
            widget: "list"
            required: false
            fields:
              - {label: "Игрок и минута", name: "event", widget: "string"}
          - label: "События Команды 2"
            name: "events2"
            widget: "list"
            required: false
            fields:
              - {label: "Игрок и минута", name: "event", widget: "string"}

      - label: "Предстоящие матчи"
        name: "upcoming"
        file: "Fakel_Site/data/upcoming.json"
        fields:
          - label: "Матчи"
            name: "matches"
            widget: "list"
            fields:
              - {label: "Дата и тур", name: "date", widget: "string"}
              - {label: "Название матча", name: "title", widget: "string"}

      - label: "Состав команды"
        name: "team_roster"
        file: "Fakel_Site/data/team.json"
        fields:
          - label: "Игроки"
            name: "players"
            widget: "list"
            fields:
              - {label: "Имя и Фамилия", name: "name", widget: "string"}
              - {label: "Номер", name: "number", widget: "string"}
              - {label: "Амплуа", name: "category", widget: "select", options: ["Вратари", "Защитники", "Полузащитники", "Нападающие"]}
              - {label: "Фотография", name: "image", widget: "image"}
              - {label: "Капитан", name: "is_captain", widget: "boolean", default: false, required: false}
              - {label: "Дата рождения", name: "birthdate", widget: "string"}
              - {label: "Рост / Вес", name: "physique", widget: "string"}
              - {label: "Рабочая нога", name: "foot", widget: "string"}
              - {label: "Дата дебюта", name: "debut", widget: "string"}
              - {label: "Статистика", name: "stats", widget: "string"}
